# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    reason: "No fixes available for node 24.12.0-alpine"
  - vulnerability: GHSA-5j98-mcp5-4vw2
    reason: "No fixes available for node 24.12.0-alpine"
  - vulnerability: GHSA-29xp-372q-xqph
    reason: "No fixes available for node 24.12.0-alpine"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
